name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Use Node.js 18.19.1
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.1'

      - name : Generate Environment Variables File for Production
        run : |
          cd catch-study
          touch .env.production
          echo REACT_APP_SERVER_URL=${{ secrets.REACT_APP_SERVER_URL }}\ >> .env.production

      - name: Install dependencies
        run: |
          cd catch-study
          yarn

      - name: React Build
        run: |
          cd catch-study
          yarn build

      - name: zip create
        run: |
          cd catch-study
          zip -qq -r ./catch-study-build.zip . -x "node_modules/*"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./catch-study-build.zip s3://catch-study-build-bucket/catch-study-build.zip
