name: CI

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18.19.1
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.1'

      - name: Install dependencies
        run: |
          cd catch-study
          yarn

      - name: Configure Git
        run: |
          git config user.name HyunJungJo98
          git config user.email kchwoonn0827@naver.com

      - name: Push to main branch
        if: success()
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GIT_TOKEN}}
